---
# Use Ubuntu 'trusty' distribution
sudo: required
# dist: trusty

# may be a useful refactor at some point
# https://docs.travis-ci.com/user/docker/

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.13.0

language: ruby

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  # - >
  #   curl -sSL "https://get.docker.com/gpg" |
  #    sudo -E apt-key add -
  # - >
  #   echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
  #    sudo tee -a /etc/apt/sources.list
  # - sudo apt-get update
  # - >
  #   sudo apt-get -o Dpkg::Options::="--force-confdef" \
  #    -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  # - docker version
  # # Update docker-compose via pip
  # - sudo pip install docker-compose

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version

before_script:
  - docker-compose -f ./docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg CACHEBUST=$(date +%s) cp-test-runner
  - docker-compose -f ./docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg CACHEBUST=$(date +%s) cp-nodejs
  - docker-compose -f ./docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg CACHEBUST=$(date +%s) cp-pg-server

  - docker-compose -f ./docker/compose/full-stack-test/docker-compose-test.yml up -d

# permissions needed, two suggestions here
# https://stackoverflow.com/questions/42154912/permission-denied-for-build-sh-file
# https://stackoverflow.com/questions/10516201/updating-file-permissions-only-in-git
# https://stackoverflow.com/questions/14267441/automatically-apply-git-update-index-chmodx-to-executable-files
script:
  # - ./docker/compose-tests.sh
  # - travis_retry ./docker/compose-tests.sh match
  - travis_retry ./docker/compose-tests.sh pause-cancel2

after_script:
  - docker-compose -f ./docker/compose/full-stack-test/docker-compose-test.yml down
