version: '2.1'

services:
  cp-test:
    # image: selenium/standalone-chrome

    # this images supports viewing test browser using a vnc viewer
    image: selenium/standalone-chrome-debug
    # image: selenium/standalone-firefox

    ports: 
      - "5900:5900"

    depends_on:
      - cp-nodejs
      - cp-pg-server
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3 # may not be needed 
    
  cp-front-end:
    build:
      context: ../../jekyll/
      args:
        REPO: https://github.com/voteamerica/voteamerica.github.io
        BRANCH_NAME: master

    ports: 
      - "4000:4000"
    depends_on:
      - cp-nodejs
      - cp-pg-server

    # https://jekyllrb.com/docs/usage/
    # command: jekyll serve -H 0.0.0.0 --watch --config _config-dev.yml
    # NOTE: .yml file needs to contain IP addresses for this network (not the usual localhost)
    # command: jekyll serve -H 0.0.0.0 --watch --config _config-local.yml 
    # command: jekyll serve -H 0.0.0.0 --watch --config /_config-local-ip.yml
    command: jekyll serve --watch --source /usr/src/app/frontend --config /_config-local-ip.yml

    # auto test
    # command: jekyll serve -H 0.0.0.0 --config _config-local.yml --watch site.api="http://10.5.0.5:8000" site.cp_site="http://10.5.0.4:4000"
    # local dev
    #command: jekyll serve -H 0.0.0.0 --watch --config --api "http://localhost:8000" --cp_site "http://localhost:4000"



    volumes:
      - ../../../../voteUSfrontend:/usr/src/app/frontend

    networks:
      vpcbr:
        ipv4_address: 10.5.0.4 # probably not needed, but keeps things in sync 

  cp-nodejs:
    build:
      context: ../../nodeApp/
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: carpool

    depends_on:
    - cp-pg-server
    # command: bash
    stdin_open: true
    tty: true
    environment:
      # - PGHOST=docker_cp-pg-server_1
      #  it may be that this is overridden by entrypoint script 
      # (or is it a dockerfile issue?)
      #  remove this and pwd from entrypoint script, 
      # also patch run commands to pass PGHOST/pwd as env var command line params

      - PGPASSWORD=pwd
      - PGHOST=10.5.0.6
    ports:
      - "8000:8000"
    links:
      - cp-pg-server

    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  cp-pg-server:
    build:
      context: ../../pg-auto
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: pgres-cp
    ports:
      - "5433:5432"

    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  cp-pg-client:
    build:
      context: ../../pg-client
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: pg-client
    depends_on:
    - cp-pg-server

    # command: bash
    stdin_open: true
    tty: true
    environment:
      - PGUSER=postgres
      # - PGUSER=carpool_web
      - PGDATABASE=carpoolvote
      - PGPASSWORD=pwd
      - PGHOST=10.5.0.6

    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  cp-test-runner:
    build:
      context: ../../nightwatch/
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: nightwatch

    depends_on:
    - cp-test
    # command: /bin/bash
    # command: /run-tests.sh match2

    stdin_open: true
    tty: true

    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

# this supports networks with static ip addresses
# http://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  node_app_node_modules:
